### ISSUE TITLE
Conflicting license declarations in README.md and LICENSE

### ISSUE THREAD

**Issue by ephphatha** [Croquetx/thecolony#2]
The readme as of ea0ff91 states the code is released under GPLv2 but the LICENSE file is for Apache-2.0, could you please clarify which license is intended?

https://github.com/Croquetx/thecolony/blob/ea0ff91311dd92b6ccb10e920b9391bc1ee21903/README.md?plain=1#L8

https://github.com/Croquetx/thecolony/blob/ea0ff91311dd92b6ccb10e920b9391bc1ee21903/LICENSE#L1-L2

**Comment by Croquetx** [comment]
Good catch.
